version: "3.9"
services:
  social-graph-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    # restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.5

  social-graph-mongodb:
    image: mongo:4.4.6
    hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    # restart: always
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    networks:
      socialnet:
        ipv4_address: 172.32.0.29

  social-graph-redis:
    image: myredis
    hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    # restart: always
    runtime: ${SERVICE_RUNTIME_REDIS}
    # command: ["redis-server", "--appendonly", "no", "--save", '""']
    networks:
      socialnet:
        ipv4_address: 172.32.0.7

  home-timeline-redis:
    image: myredis
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    # restart: always
    runtime: ${SERVICE_RUNTIME_REDIS}
    # command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      socialnet:
        ipv4_address: 172.32.0.15

  compose-post-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.16

  post-storage-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: post-storage-service
    # ports:
    #   - 10002:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.8


  post-storage-memcached:
    image: memcached
    hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    # restart: always
    runtime: ${SERVICE_RUNTIME_MEMCACHED}
    networks:
      socialnet:
        ipv4_address: 172.32.0.19

  post-storage-mongodb:
    image: mongo:4.4.6
    hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    # restart: always
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    networks:
      socialnet:
        ipv4_address: 172.32.0.21

  user-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.22

  user-timeline-redis:
    image: myredis
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    # restart: always
    runtime: ${SERVICE_RUNTIME_REDIS}
    # command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      socialnet:
        ipv4_address: 172.32.0.6

  user-timeline-mongodb:
    image: mongo:4.4.6
    hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    # restart: always
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    networks:
      socialnet:
        ipv4_address: 172.32.0.10

  url-shorten-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    # restart: always
    entrypoint: UrlShortenService
    depends_on:
      jaeger-agent:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.25

  url-shorten-memcached:
    image: memcached
    hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    # restart: always
    runtime: ${SERVICE_RUNTIME_MEMCACHED}
    networks:
      socialnet:
        ipv4_address: 172.32.0.4

  url-shorten-mongodb:
    image: mongo:4.4.6
    hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    # restart: always
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    networks:
      socialnet:
        ipv4_address: 172.32.0.24

  user-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-service
    #    ports:
    #      - 10005:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.17

  user-memcached:
    image: memcached
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    # restart: always
    runtime: ${SERVICE_RUNTIME_MEMCACHED}
    networks:
      socialnet:
        ipv4_address: 172.32.0.12

  user-mongodb:
    image: mongo:4.4.6
    hostname: user-mongodb
    # ports:
    #   - 27023:27017
    # restart: always
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    networks:
      socialnet:
        ipv4_address: 172.32.0.11

  # media-service:
  #   image: deathstarbench/social-network-microservices:latest
  #   hostname: media-service
  #   #    ports:
  #   #      - 10006:9090
  #   depends_on:
  #     jaeger-agent:
  #       condition: service_started
  #     media-mongodb:
  #       condition: service_started
  #   # restart: always
  #   entrypoint: MediaService
  #   volumes:
  #     - ./config:/social-network-microservices/config
  #   runtime: ${SERVICE_RUNTIME}
  #   networks:
  #     socialnet:
  #       ipv4_address: 172.32.0.3

  # media-memcached:
  #   image: memcached
  #   hostname: media-memcached
  #   #    ports:
  #   #      - 11215:11211
  #   runtime: ${SERVICE_RUNTIME_MEMCACHED}
  #   # restart: always
  #   networks:
  #     socialnet:
  #       ipv4_address: 172.32.0.41

  # media-mongodb:
  #   image: mongo:4.4.6
  #   hostname: media-mongodb
  #   #    ports:
  #   #      - 27024:27017
  #   # restart: always
  #   networks:
  #     socialnet:
  #       ipv4_address: 172.32.0.40

  text-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: text-service
    #    ports:
    #      - 10007:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: TextService
    runtime: ${SERVICE_RUNTIME}
    volumes:
      - ./config:/social-network-microservices/config
    networks:
      socialnet:
        ipv4_address: 172.32.0.13

  unique-id-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    # restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.2

  user-mention-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      jaeger-agent:
        condition: service_started
    # restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.20

  home-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      jaeger-agent:
        condition: service_started
    # restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    runtime: ${SERVICE_RUNTIME}
    networks:
      socialnet:
        ipv4_address: 172.32.0.23

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    depends_on:
      jaeger-agent:
        condition: service_started
    # restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
    networks:
      socialnet:
        ipv4_address: 172.32.0.30

  # media-frontend:
  #   image: yg397/media-frontend:xenial
  #   hostname: media-frontend
  #   ports:
  #     - 8081:8080
  #   restart: always
  #   depends_on:
  #     jaeger-agent:
  #       condition: service_started
  #   volumes:
  #     - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
  #     - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  #   networks:
  #     socialnet:
  #       ipv4_address: 172.32.0.31

  jaeger-agent:
    image: jaegertracing/all-in-one:latest
    cpuset: "0-10"  # Bind to CPUs 1 and 2
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - 16686:16686
      #      - 14268:14268
      #      - 9411:9411
    # restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      socialnet:
        ipv4_address: 172.32.0.28
networks:
  socialnet:
    external: true
